### ISSUE TITLE
MessageBus.java

### ISSUE THREAD

**Issue by evan-choi** [UnsignedUSB/MessageBus#5]
파일이 없는거같습니다.

**Comment by UnsignedUSB** [comment]
최소 한개의 Method에 Subscribe해준다면 해당 파일이 자동으로 생성되는 구조입니다.
한번 생성되면 계속 사용할 수 있는 구조이긴 하지만, 최초가 좀 마음에 안들어서 개선을 고민중입니다.

**Comment by SteaI** [comment]
그럼 Subscribe후 빌드를 한번 해줘야지
MessageBus를 사용할 수 있다는건가요?

빌드전에 Subscribe하고 MessageBus를 참조하려니 안되기에 문의드렸습니다

**Comment by UnsignedUSB** [comment]
네. MessageBus는 Annotation Processor로써 빌드타임에 코드가 분석되어 필요한 파일이 생성됩니다.

2018. 2. 19. 오전 10:04에 "Steal" <notifications@github.com>님이 작성:
